apiVersion: v1
kind: Secret
metadata:
  name: vector-docs-secret
  namespace: vector-docs
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  JWT_SECRET: "secret"
  APP_CHAT_API_KEY: "secret"
  SPRING_MAIL_USERNAME: "example@gmail.com"
  SPRING_MAIL_PASSWORD: "secret"
